CREATE TABLE `users`  (
  `id` bigint UNSIGNED NOT NULL,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `birthday` date NULL,
  `card_id` varchar(255) NOT NULL,
  `mark` varchar(255) NOT NULL,
  `parther_id` int UNSIGNED NOT NULL,
  `group_id` int UNSIGNED NOT NULL,
  `nickname` varchar(255) NOT NULL,
  `avatar` varchar(255) NOT NULL,
  `phone` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `add_ip` varchar(255) NOT NULL,
  `last_time` datetime NULL,
  `last_ip` varchar(255) NOT NULL,
  `money` decimal(10, 2) NOT NULL,
  `brokerage_price` decimal(10, 2) NOT NULL,
  `integral` int UNSIGNED NOT NULL,
  `exp` decimal(10, 2) NOT NULL,
  `sign_num` int UNSIGNED NOT NULL,
  `state` tinyint UNSIGNED NOT NULL,
  `level` tinyint UNSIGNED NOT NULL,
  `agent_level` int UNSIGNED NOT NULL,
  `is_spread` tinyint UNSIGNED NOT NULL,
  `spread_user` bigint UNSIGNED NOT NULL,
  `spread_time` datetime NULL,
  `user_type` varchar(255) NOT NULL,
  `is_promoter` tinyint UNSIGNED NOT NULL,
  `pay_count` int UNSIGNED NOT NULL,
  `spread_count` int UNSIGNED NOT NULL,
  `clean_time` datetime NULL,
  `address` varchar(255) NOT NULL,
  `admin_id` int UNSIGNED NOT NULL,
  `login_type` tinyint UNSIGNED NOT NULL,
  `record_phone` varchar(255) NOT NULL,
  `member_level` tinyint UNSIGNED NOT NULL,
  `member_ever` tinyint UNSIGNED NOT NULL,
  `overdue_time` date NULL,
  `division_type` tinyint UNSIGNED NOT NULL,
  `division_status` tinyint UNSIGNED NOT NULL,
  `is_division` tinyint UNSIGNED NOT NULL,
  `is_agent` tinyint UNSIGNED NOT NULL,
  `is_staff` tinyint UNSIGNED NOT NULL,
  `division_id` int UNSIGNED NOT NULL,
  `agent_id` int NOT NULL,
  `staff_id` int NOT NULL,
  `division_percent` tinyint UNSIGNED NOT NULL,
  `division_change` datetime NULL,
  `division_end_time` datetime NULL,
  `division_invite` int UNSIGNED NOT NULL,
  `created_at` datetime NULL DEFAULT NULL,
  `updated_at` datetime NULL DEFAULT NULL,
  `deleted_at` datetime NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `users_state`(`state`),
  INDEX `users_spread_user`(`spread_user`),
  INDEX `users_is_promoter`(`is_promoter`),
  UNIQUE `users_username_unique`(`username`)
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;